---
title: 'Modeling Cricket Data Analysis With Bioclimactic Variables'
author: "Stefan Wagner"
subtitle: ''
output:
  html_document:
    css: lab.css
---

```{r setup, include=FALSE}
# Setup the environment
library(knitr)
knitr::opts_chunk$set(fig.align='center',fig.width=10, fig.height=6, fig.path='Figs/',  warning=FALSE, echo=TRUE, eval=TRUE, message=FALSE)

r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)
```

```{r, echo=F, eval=T}
packagesNeeded<-c('dismo', 'tidyverse', 'raster', 'sf', 'sp', 'rJava', 'ggplot2')
# installed packages
packages<-installed.packages()
# if the package is not installed, install it
for(package in packagesNeeded){
if (!(package %in% packages)){
    install.packages(package)
 }}
```

1. Cleaning and formatting occurence data

```{r}
data <- ("C:/MaxEnt_Modeling/R_Script/Cricket-Data-Analysis--main/")
# Reading CSV Files 
csv_files <- list.files(path = data, pattern = "\\.csv$", full.names = T, recursive = T)
```

Modeling state at a time limits number of useable cells, drawing from the repo and merging into a holistic df allows for more usable cells (MaxEnt requests 10,000)


```{r}
library(tidyverse)
#function to combine all observations dataframes into one dataframe for analysis
read_obs <- function(file) {
  df <- read_csv(file)
  
  # read file name without csv - statename 
  state_name <- tools::file_path_sans_ext(basename(file)) %>%
    str_remove("_observations")
  
  df <- df %>%
    mutate(state_file = state_name)
  
  return(df)  

}
# combining csv files on row-wise
occurences <- map_dfr(csv_files, read_obs)
glimpse(occurences)
```

```{r}
western_states <- c(
  "Arizona", 
  "California", 
  "Colorado", 
  "Idaho", 
  "Kansas", 
  "Montana", 
  "Nebraska",
  "Nevada",
  "New Mexico",
  "North Dakota",
  "Oklahoma",
  "Oregon",
  "South Dakota",
  "Texas",
  "Utah",
  "Washington",
  "Wyoming"
  )
```

```{r}
library(raster)
library(sf)
library(tidyverse)

raster_path = "c:/MaxEnt_Modeling/R_Script/wc2.1_10m_bio/"
#reading raster files
#Bioclim Variables 1970-2000 on 10m resolution
#future cross referencing resolution with model prediction?
raster <- list.files(path = raster_path, pattern = "\\.tif$", full.names = T)
#creating raster stack object
raster_stack_western <- raster::stack(raster)

# clipping US Shapefile to raster_stack object
states<-st_read("C:/MaxEnt_Modeling/R_Script/cb_2018_us_state_5m.shp")
west <- states %>%
  filter(NAME %in% western_states)

west_prj <- st_transform(west, crs(raster_stack_western))
west_spatial <- as(west_prj, "Spatial")

west.bio_crop<-crop(raster_stack_western, west_spatial)
west.bio_mask<-mask(west.bio_crop, west_spatial)

west.bio_df<-as.data.frame(west.bio_mask)

### Plotting R Stack for visualization?
plot(west.bio_mask)

###
```

https://cran.r-project.org/web/packages/dismo/dismo.pdf

2. Base MaxEnt model

```{r}
library(dismo)
require(rJava)
library(sp)

# removing lat long na values
occurences <- occurences %>%
  filter(!is.na(latitude), !is.na(longitude))

# make occurrences sf then sf SPDF
west.occurence_sf <- st_as_sf(occurences, coords = c("longitude", "latitude"), crs = 4326)
west.occurence_sp <- as(west.occurence_sf, "Spatial")
# occurences to same spatial reference as bioclim 
west.occurence_sp <- spTransform(west.occurence_sp, crs(west.bio_mask))

raster_values<-raster::extract(west.bio_mask, west.occurence_sp)
clean_points<-na.omit(raster_values)

# only want rows with valid raster values
west.occurence_cleaned <- occurences %>%
  filter(complete.cases(raster_values))
# same thing to SPDF object
cases <- complete.cases(raster_values)
west.occurence_sp_clean <- west.occurence_sp[cases, ]
# Model
western.model <- dismo::maxent(x=west.bio_mask, p = west.occurence_sp_clean)
plot(western.model)
```

3. Plotting out Clim Vars of interest

```{r}
#NOTE: Very interested in BIO19 | BIO6
library(RColorBrewer)

bio19 <- west.bio_mask[["wc2.1_10m_bio_19"]]
bio19_df <- as.data.frame(bio19, xy = TRUE, na.rm = TRUE)
plot(bio19)

ggplot(data = bio19_df, aes(x = x, y = y, color = wc2.1_10m_bio_19)) +
  coord_fixed() +
  geom_point()+
  theme_minimal()

bio6 <- west.bio_mask[["wc2.1_10m_bio_6"]]
bio6_df <- as.data.frame(bio6, xy = TRUE, na.rm = TRUE)
plot(bio6)

ggplot(data = bio6_df, aes(x = x, y = y, color = wc2.1_10m_bio_6)) +
  coord_fixed()+
  geom_point()+
  theme_minimal()


```


4. Testing for suitability & cross-validation of model?

```{r}
library(ggplot2)

suitability <- predict(western.model, west.bio_mask)
plot(suitability)
```

4.5 Using Dismo Bioclim?

```{r}
library(dismo)
library(geodata)


```

5. K-fold testing

```{r}
library(spatstat)

xy = coordinates(occurences)
suitPPP <- ppp(xy[,1], xy[,2], range(xy[,1]), range(xy[,2]))
suitPPP.km <- rescale(ppp(xy[,1], xy[,2], range(xy[,1]), range(xy[,2])), 1000, "km")

envelope(suitPPP.km, nsim = 50)
plot(envelope(suitPPP.km, Kest, nsim=50))

```

